services:
  app:
    image: hatrongvu/archetype
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      GRPC_SERVER_PORT: 9090
      GRPC_SERVER_SECURITY: false
      SECURITY_AUTHENTICATION_JWT_SECRET: OGEzMWZkOTQzYTI3ZjMwNTJmNTEwYjUwZjMxN2ZiOTljODgyODhkNTkwMzllYWIyYjVhOTMzNzZkYzM4MzI0NDFmMzJhNmQwZTExNjU3ZTBkZmNmZTY2MzlkYjVlZmNlMjI0M2Y3MWUzN2YwMjczYTU4YmFjZGU0M2MzNzZiNDc=
      JWT_TOKEN_VALIDITY_IN_SECONDS: 86400
      APPLICATION_PORT: 8080
      DATABASE_POSTGRES_IP: 192.168.1.10
      POSTGRES_PORT: 5432
      DATABASE_SCHEMA: user-manager
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
      HIBERNATE_DDL_AUTO: create-drop